require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# target 'rn_fashion_app' do
#   config = use_native_modules!

#   use_react_native!(:path => config["reactNativePath"])

pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

#   target 'rn_fashion_appTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
# end


abstract_target 'App' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  target 'rn_fashion_app' do
    #Production-specific pods
    target 'rn_fashion_appTests' do
      inherit! :complete
      # Pods for testing
    end
  end
  target 'RN Fashion Staging' do
    #Development-specific pods
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
