# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


#########################################################################################
########################################## ANDROID ######################################
#########################################################################################

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the application"
  lane :beta do
    versioncode = increment_version_code
    versionname = increment_version_name(
      gradle_file_path: "./android/app/build.gradle",
      version_name: ENV["VERSION"]
    )
    version_name = get_version_name(
      gradle_file_path: "./android/app/build.gradle",
      ext_constant_name:"versionName"
    )
    gradle(task: "app:assembleRelease", project_dir: "android/")
    puts versioncode
    puts version_name
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
