export default {
  textPrimaryColor: '#0C0D34',
  primatyBtnBg: '#2CB9B0',
  secondaryBg: 'rgba(12, 13, 52, .5)',
  white: '#fff',
  bodyText: 'rgba(12, 13, 53, .7)',
  'slide.grey': '#F4F0EF',
  danger: '#FF0058',
  darkGrey: '#8A8D90',
  primaryLight: '#E8F9F0',
  transparent: 'transparent',
  orange: 'orange',
  yellow: '#a09c00',
  pink: 'pink',
  violet: 'violet',
  lightGrey: '#fafafa',
  lightBlue: '#5ea3c6',
  overlay: 'rgba(0, 0, 0, .6)',
};
